version: 2.1
jobs:

  build:
    docker:
      - image: circleci/php:7.4
      
    working_directory: ~/federatedcanada
      
    steps:
      - checkout
      - run: composer install
      - run: composer test